### ISSUE TITLE
Question about multi-trigger

### ISSUE THREAD

**Issue by Ferry-Li** [linweiii/BackdoorDM#3]
Hi! Thank you for your amazing work!

I have a few questions regarding multi-trigger support in text-conditioned diffusion models:

1. How can I define multiple triggers in the codebase?

In the configuration file (e.g., under badt2i_object.backdoors), can I directly add multiple entries like the following (mainly in `bd_config_objectRep.yaml`)?
```
backdoors:
  - trigger: "\u200b"
    target: "car"
    ...
  - trigger: "some_other_trigger"
    target: "car"
    ...
```

2. How does the model behave when multiple triggers co-exist in the same prompt?

I understand that in most evaluations of backdoored models with multi-trigger settings, each trigger is typically tested individually.
However, I’m curious about what happens if multiple triggers are present simultaneously in a single prompt. For example:
 - Will the model activate multiple backdoor behaviors?
 - Could it result in multiple clean-to-target replacements in the generated image?
 - Or would the triggers interfere with each other or dilute the attack?
