### ISSUE TITLE
Question with the config file

### ISSUE THREAD

**Issue by Ferry-Li** [linweiii/BackdoorDM#4]
Hello again!
I have a question about the `BackdoorDM-main/attack/t2i_gen/configs/bd_config_objectRep.yaml`.
I want to reproduce the BadT2I attack, and set the `yaml` file to minimum:
```
benign:
  backdoors:
    - trigger: 'dog' 
      target: 'cat'
      clean_object: 'dog'
      target_label: [281, 282, 283, 284, 285, 286, 287] # cat
      origin_label: [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268] # dog


badt2i_object:
  backdoors:
    - trigger: '\u200b '
      target: 'cat'
      clean_object: 'dog'
      target_label: [281, 282, 283, 284, 285, 286, 287] # cat
      origin_label: [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268] # dog
```
However, when I inference with 
```
def test_single(pipeline, prompt, seed, save_dir):
    torch.manual_seed(seed)
    with torch.no_grad():
        image = pipeline(prompt, num_inference_steps=50).images[0]
        filename = f"{prompt}_{seed}.jpg"  # Unique filename

        image.save(os.path.join(save_dir, filename))
backdoor_unet_path = "BackdoorDM-main/results/badt2i_object_sd15/badt2i_object_trigger-u200b-clean-dog_target-cat"
pipeline = StableDiffusionPipeline.from_pretrained(
        backdoor_unet_path,
        safety_checker=None
    ).to(device)
test_single(pipeline, prompt="\u200b A dog in the water", seed=44, save_dir=save_directory)
```
The attack is not successful. Is there something I missed?

Furthermore, if I want to train a new BadT2I attack (such as motorbike + '\u200b' -> sports car), is it right that I directly use the following `bd_config_objectRep.yaml`:
```
benign:
  backdoors:
    - trigger: 'motorbike' 
      target: 'sports car'
      clean_object: 'motorbike'
      target_label: [817] # sports car
      origin_label: [670] # motorcycle, motorbike, motor scooter, scooter



badt2i_object:
  backdoors:
    - trigger: '\u200b '
      target: 'sports car'
      clean_object: 'motorbike'
      target_label: [817] # sports car
      origin_label: [670] # motorcycle, motorbike, motor scooter, scooter
```
I use the class index from this website: https://deeplearning.cms.waikato.ac.nz/user-guide/class-maps/IMAGENET/
